version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - bodyclose
    - contextcheck
    - containedctx
    - errorlint
    - gocognit
    - goconst
    - godox
    - maintidx
    - misspell
    - nestif
    - sqlclosecheck
    - testifylint
    - unparam
    - whitespace
    - wrapcheck

formatters:
  enable:
    - gofmt
    - goimports