version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: vigilo-identity
    main: ./  # Set the main directory for your Go module
    mod: true # Ensure Go Modules are used
    goos:
      - linux
      - darwin
    goarch:
      - amd64

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

files:
  - src: ./identity/**/*  # Include all files from the identity directory
    dst: ./identity/      # Ensure this is included in the release
