version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: vigilo-identity
    skip: true  # Skipping build for this library since it's not creating an executable

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

project_name: vigilo

files:
  - src: ./identity/**
    dst: identity/
