project_name: vigilo

builds:
  - ignore: true
  - main: ./cmd/vigilo
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags: "-s -w"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - ./**

release:
  github:
    owner: vigiloauth
    name: vigilo
