version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: vigilo-identity
    skip: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
