version: 2

builds:
  - id: vigilo
    skip: true

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_source.tar.gz"
    files:
      - ./pkg/**/*

release:
  github:
    owner: vigiloauth
    name: vigilo