builds:
  - id: vigilo_build
  - skip: true
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags: "-s -w"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_source.tar.gz"
    files:
      - ./pkg/**/*

release:
  github:
    owner: vigiloauth
    name: vigilo
