FROM golang:1.23.3 AS builder
WORKDIR /app
COPY . .

ENV GOOS=linux
ENV GOARCH=amd64
ENV CGO_ENABLED=0

RUN go build -o /app/identity-server ./cmd/identity-server

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/identity-server .
COPY cmd/config/application/config.yaml ./config.yaml
RUN chmod +x ./identity-server
EXPOSE 8080

ARG SMTP_USERNAME
ARG SMTP_FROM_ADDRESS
ARG SMTP_PASSWORD
ARG TOKEN_ISSUER
ARG TOKEN_PRIVATE_KEY
ARG TOKEN_PUBLIC_KEY
ARG CRYPTO_SECRET_KEY

ENV SMTP_USERNAME=$SMTP_USERNAME
ENV SMTP_FROM_ADDRESS=$SMTP_FROM_ADDRESS
ENV SMTP_PASSWORD=$SMTP_PASSWORD
ENV TOKEN_ISSUER=$TOKEN_ISSUER
ENV TOKEN_PRIVATE_KEY=$TOKEN_PRIVATE_KEY
ENV TOKEN_PUBLIC_KEY=$TOKEN_PUBLIC_KEY
ENV CRYPTO_SECRET_KEY=$CRYPTO_SECRET_KEY

ENV VIGILO_SERVER_MODE=docker
CMD ["./identity-server"]
