package common

const (
	ClientID                      string = "client_id"
	ClientSecret                  string = "client_secret"
	RedirectURI                   string = "redirect_uri"
	Scope                         string = "scope"
	State                         string = "state"
	XForwardedHeader              string = "X-Forwarded-For"
	Approved                      string = "approved"
	GrantType                     string = "grant_type"
	ClientCredentials             string = "client_credentials"
	BearerAuthHeader              string = "Bearer "
	Authorization                 string = "Authorization"
	SessionToken                  string = "vigilo-auth-session-token"
	ResponseType                  string = "response_type"
	AuthzCode                     string = "code"
	Location                      string = "Location"
	ClientRegistrationAccessToken string = "registration_access_token"
	CacheControl                  string = "Cache-Control"
	NoStore                       string = "no-store"
	RequestIDHeader               string = "X-Request-ID"
	RequestID                     string = "requestID"
	CodeChallenge                 string = "code_challenge"
	CodeChallengeMethod           string = "code_challenge_method"
	Username                      string = "username"
	Password                      string = "password"
	CodeVerifier                  string = "code_verifier"
	RefreshToken                  string = "refresh_token"
	Token                         string = "token"
	BasicAuthHeader               string = "Basic "
	FromAddress                   string = "From"
	EmailSubject                  string = "Subject"
	Recipient                     string = "To"
	HTMLBody                      string = "text/html"
	VerifyEmailAddress            string = "Verify Your Email Address"
)
