# .github/workflows/docker-build-push.yml
name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      version:
        description: 'Version of the release'
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  build_and_push_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # Build and push Docker image using the version passed as input
      - name: Build and push Docker image
        run: |
          docker build -t vigiloauth/server:${{ inputs.version }} .
          docker push vigiloauth/server:${{ inputs.version }}
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          VERSION: ${{ inputs.version }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
