name: golangci-lint

on:
  push:
    branches: [ master ]
    paths:
      - 'identity/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches: [ '*' ]
    paths:
      - 'identity/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'

permissions:
  contents: read

jobs:
  golangci:
    strategy:
      matrix:
        module:
          - identity
          - root
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Set up Go modules
        run: |
          if [ "${{ matrix.module }}" == "root" ]; then
            go mod tidy
          else
            cd ./${{ matrix.module }}
            go mod tidy
          fi

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: ${{ matrix.module == 'root' && './' || './identity' }}
          args: --out-format=github-actions --timeout=5m --concurrency=4 --max-issues-per-linter=0
