name: Release

on:
  push:
    branches: [ master ]

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Create .env file
        run: |
          echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> .env
          echo "SMTP_FROM_ADDRESS=${{ secrets.SMTP_FROM_ADDRESS }}" >> .env
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env
          echo "TOKEN_ISSUER=${{ secrets.TOKEN_ISSUER }}" >> .env
          echo "TOKEN_PRIVATE_KEY=${{ secrets.TOKEN_PRIVATE_KEY }}" >> .env
          echo "TOKEN_PUBLIC_KEY=${{ secrets.TOKEN_PUBLIC_KEY }}" >> .env
          echo "CRYPTO_SECRET_KEY=${{ secrets.CRYPTO_SECRET_KEY }}" >> .env

      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/github

      - name: Run semantic-release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}
        run: |
          result=$(npx semantic-release)
          echo "$result"

          version=$(echo "$result" | grep -oP 'Published release \K[^\s]+')

          if [[ -n "$version" ]]; then
            echo "new_release_published=true" >> $GITHUB_OUTPUT
            echo "new_release_version=$version" >> $GITHUB_OUTPUT
          else
            echo "new_release_published=false" >> $GITHUB_OUTPUT
          fi

      - name: Exit if no new release
        if: steps.semantic.outputs.new_release_published == 'false'
        run: echo "No new release published. Exiting gracefully."
        continue-on-error: true

      - name: Fetch tags
        if: steps.semantic.outputs.new_release_published == 'true'
        run: git fetch --tags origin

      - name: Debug Docker Build
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo "New release published: ${{ steps.semantic.outputs.new_release_published }}"
          echo "New version: ${{ steps.semantic.outputs.new_release_version }}"
          echo "ENV version: ${{ env.NEW_RELEASE_VERSION }}"
          # List Docker images
          docker images

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        if: steps.semantic.outputs.new_release_version != ''
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            vigiloauth/server:${{ steps.semantic.outputs.new_release_version }}
            vigiloauth/server:latest
          build-args: |
            SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}
            SMTP_FROM_ADDRESS=${{ secrets.SMTP_FROM_ADDRESS }}
          secrets: |
            "smtp_password=${{ secrets.SMTP_PASSWORD }}"
            "token_issuer=${{ secrets.TOKEN_ISSUER }}"
            "token_private_key=${{ secrets.TOKEN_PRIVATE_KEY }}"
            "token_public_key=${{ secrets.TOKEN_PUBLIC_KEY }}"
            "crypto_secret_key=${{ secrets.CRYPTO_SECRET_KEY }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max