name: GoReleaser Library Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Install GoReleaser
        run: |
          curl -sSL https://github.com/goreleaser/goreleaser/releases/download/v1.15.0/goreleaser_1.15.0_Linux_x86_64.tar.gz | tar -xz
          sudo mv goreleaser /usr/local/bin

      - name: Run GoReleaser
        run: ./goreleaser release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
