name: Release

on:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened
      - closed
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.3'

      - name: Install GoReleaser
        run: |
          curl -sL https://github.com/goreleaser/goreleaser/releases/download/v1.0.0/goreleaser_Linux_x86_64.tar.gz | tar -xzv
          sudo mv goreleaser /usr/local/bin/

      - name: Determine version from PR labels
        id: version
        run: |
          PR_NUMBER=$(echo "${GITHUB_REF}" | sed -E 's/refs\/heads\///')
          LABELS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/labels")
          
          VERSION="v0.0.1"
          MAJOR=0
          MINOR=0
          PATCH=0

          if echo "$LABELS" | grep -q '"milestone"'; then
            MINOR=$((MINOR+1))
            PATCH=0
            VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          elif echo "$LABELS" | grep -q '"hotfix"'; then
            PATCH=$((PATCH+1))
            VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          elif echo "$LABELS" | grep -q '"feature"'; then
            PATCH=$((PATCH+1))
            VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          fi

          echo "Determined version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Run GoReleaser
        run: goreleaser release --rm-dist --config .goreleaser.yml --version ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
