name: Run Tests

on:
  pull_request:
    branches: [ '*' ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
        
      - name: Create .env.test file
        run: |
          echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> .env.test
          echo "SMTP_FROM_ADDRESS=${{ secrets.SMTP_FROM_ADDRESS }}" >> .env.test
          echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> .env.test
          echo "TOKEN_ISSUER=${{ secrets.TOKEN_ISSUER }}" >> .env.test
          echo "TOKEN_PRIVATE_KEY=${{ secrets.TOKEN_PRIVATE_KEY }}" >> .env.test
          echo "TOKEN_PUBLIC_KEY=${{ secrets.TOKEN_PUBLIC_KEY }}" >> .env.test
          echo "CRYPTO_SECRET_KEY=${{ secrets.CRYPTO_SECRET_KEY }}" >> .env.test

      - name: Install necessary dependencies
        run: go mod tidy

      - name: Run service folder unit tests with coverage
        run: go test -coverprofile=service-tests.out ./internal/service/...

      - name: Run repository folder unit tests with coverage
        run: go test -coverprofile=repository-tests.out ./internal/repository/...

      - name: Run integration tests with coverage
        run: go test -coverprofile=integration-tests.out ./tests/...

      - name: Upload all coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            service-tests.out
            repository-tests.out
            integration-tests.out